### DISCUSSION TITLE
Window resize is not working

### DISCUSSION THREAD

**Discussion by jk-1** [keepassxreboot/keepassxc#9589] [Q&A] [answered]
Window resize is not working. I attached second (larger) monitor to my laptop and the KeepassXC GUI is too large with too large icons, buttons and texts.
An it seems to be impossible to resize.

Mode is Compact.

How can I fix this issues or is this a bug?

----
KeepassXC was installed with these [instructions](https://www.linuxcapable.com/how-to-install-keepassxc-on-ubuntu-linux/)

```
sudo add-apt-repository ppa:phoerious/keepassxc -y

sudo apt update

apt show keepassxc
Package: keepassxc
Version: 2.7.5-1ppa1~jammy1

sudo apt install keepassxc

```

Environment is as follows:

```
uname -a
Linux ilves 6.2.0-10010-tuxedo #12 SMP PREEMPT_DYNAMIC Mon Jun 12 22:06:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```
[Tuxedo 6.2.0 is based on Ubuntu 22.04](https://distrowatch.com/table.php?distribution=tuxedo)

HW

```
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics vendor: Tongfang Hongkong
    driver: i915 v: kernel bus-ID: 00:02.0
  Device-2: NVIDIA GA107M [GeForce RTX 3050 Ti Mobile]
    vendor: Tongfang Hongkong driver: nvidia v: 530.41.03 bus-ID: 01:00.0
  Device-3: Chicony FHD Webcam type: USB driver: uvcvideo bus-ID: 3-6:5
  Display: server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 resolution: 1: 2560x1440~120Hz
    2: 2560x1440~90Hz
  OpenGL: renderer: Mesa Intel Graphics (ADL GT2) v: 4.6 Mesa 23.0.3
    direct render: Yes

```
