### ISSUE TITLE
Improve translator documentation in CONTRIBUTING 

### ISSUE THREAD

**Issue by C0rn3j** [keepassxreboot/keepassxc#10300]
Entrys is obviously not a word, it would be nice if this was done properly instead and showed Entry/Entries based on the actual count, and the same for all the other words.

In English this is super simple:
* `1` entry
* `not 1` entries.

In other languages this is more complex and has to be kept in mind if translations are meant to be perfect too, for example Czech:
* `1` záznam
* `2` záznamy
* `5` záznamů

And then there's declension.

While we are at it, there's currently inconsistent capitalization, to point out one case:  
`Delete Entry` vs  
`Move   entry`

Outside of `share/translations`, all the occurrences in the current master for entry(s) are as follows:

```yaml
# grep -Ri '(s)' # and then some additional manual filtering for comments and functions
src/cli/Analyze.cpp:            out << QObject::tr("Password for '%1' has been leaked %2 time(s)!", "", count).arg(path).arg(count) << endl;
src/cli/Clip.cpp:        lastLine = QObject::tr("Clearing the clipboard in %1 second(s)...", "", timeout).arg(timeout);
src/cli/Command.cpp:        err << QObject::tr("Missing positional argument(s).") << "\n\n";
src/core/PasswordHealth.cpp:        health->addScoreReason(QObject::tr("Password is used %1 time(s)", "", count).arg(QString::number(count)));
src/core/PasswordHealth.cpp:                health->addScoreReason(QObject::tr("Password expires in %1 day(s)", "", days).arg(days));
src/core/Tools.cpp:            return QObject::tr("over %1 year(s)", nullptr, years).arg(years);
src/core/Tools.cpp:            return QObject::tr("about %1 month(s)", nullptr, months).arg(months);
src/core/Tools.cpp:            return QObject::tr("%1 week(s)", nullptr, weeks).arg(weeks);
src/core/Tools.cpp:            return QObject::tr("%1 day(s)", nullptr, days).arg(days);
src/core/Tools.cpp:            return QObject::tr("%1 hour(s)", nullptr, hours).arg(hours);
src/core/Tools.cpp:        return QObject::tr("%1 minute(s)", nullptr, minutes).arg(minutes);
src/fdosecrets/objects/Service.cpp:            tr(R"(%n Entry(s) was used by %1)", "%1 is the name of an application", secrets.size())
src/format/KdbxXmlReader.cpp:        qWarning("KdbxXmlReader::readDatabase: found %d invalid group reference(s)", m_tmpParent->children().size());
src/format/KdbxXmlReader.cpp:        qWarning("KdbxXmlReader::readDatabase: found %d invalid entry reference(s)", m_tmpParent->children().size());
src/gui/Clipboard.cpp:        QObject::tr("Clearing the clipboard in %1 second(s)…", "", m_secondsToClear).arg(m_secondsToClear));
src/gui/DatabaseWidget.cpp:                    tr("Entries expiring within %1 day(s)", "", expirationOffset).arg(expirationOffset);
src/gui/EditWidgetIcons.cpp:        fileDialog()->getOpenFileNames(this, tr("Select Image(s)"), FileDialog::getLastDir("icons"), filter);
src/gui/EditWidgetIcons.cpp:            msg = tr("Successfully loaded %1 of %n icon(s)", "", filenames.size()).arg(numloaded);
src/gui/EditWidgetIcons.cpp:            msg += "\n" + tr("%n icon(s) already exist in the database", "", numexisting);
src/gui/EditWidgetIcons.cpp:            emit messageEditEntry(msg + "\n" + tr("The following icon(s) failed:", "", errornames.size()) + "\n"
src/gui/GuiTools.cpp:                prompt = QObject::tr("Do you really want to delete %n entry(s) for good?", "", entries.size());
src/gui/GuiTools.cpp:                                               QObject::tr("Delete entry(s)?", "", entries.size()),
src/gui/GuiTools.cpp:                prompt = QObject::tr("Do you really want to move %n entry(s) to the recycle bin?", "", entries.size());
src/gui/GuiTools.cpp:                                               QObject::tr("Move entry(s) to recycle bin?", "", entries.size()),
src/gui/GuiTools.cpp:                            "Entry \"%1\" has %2 reference(s). "
src/gui/MainWindow.cpp:            m_ui->actionEntryRestore->setText(tr("Restore Entry(s)", "", dbWidget->numberOfSelectedEntries()));
src/gui/MainWindow.cpp:            m_ui->actionEntryRestore->setToolTip(tr("Restore Entry(s)", "", dbWidget->numberOfSelectedEntries()));
src/gui/MainWindow.cpp:        m_statusBarLabel->setText(tr("%1 Entry(s)", "", numEntries).arg(numEntries));
src/gui/MainWindow.ui:    <string notr="true" extracomment="Translatable string with plural form set in CPP file">Restore Entry(s)</string>
src/gui/TotpDialog.cpp:    m_ui->timerLabel->setText(tr("Expires in <b>%n</b> second(s)", "", m_step - (epoch % m_step)));
src/gui/csvImport/CsvImportWidget.cpp:        m_ui->messageWidget->showMessage(tr("Error(s) detected in CSV file!").append("\n").append(formatStatusText()),
src/gui/csvImport/CsvImportWidget.cpp:        return text.section('\n', 0, 1).append("\n").append(tr("[%n more message(s) skipped]", "", items - 2));
src/gui/csvImport/CsvParserModel.cpp:                  .arg(tr("%n byte(s)", nullptr, getFileSize()),
src/gui/csvImport/CsvParserModel.cpp:                       tr("%n row(s)", nullptr, getCsvRows()),
src/gui/csvImport/CsvParserModel.cpp:                       tr("%n column(s)", nullptr, qMax(0, getCsvCols() - 1))));
src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp:                            tr("Successfully removed %n encryption key(s) from KeePassXC settings.", "", count),
src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp:                                tr("Successfully removed permissions from %n entry(s).", "", counter),
src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp:    m_ui->parallelismSpinBox->setSuffix(tr(" thread(s)", "Threads for parallel execution (KDF settings)", value));
src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.cpp:        this, tr("Purged Unused Icons"), tr("Purged %n icon(s) from the database.", "", purgeCounter), MessageBox::Ok);
src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.ui:           <string>Delete selected icon(s)</string>
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n hour(s)", nullptr, 12))->setData(QVariant::fromValue(TimeDelta::fromHours(12)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n hour(s)", nullptr, 24))->setData(QVariant::fromValue(TimeDelta::fromHours(24)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n week(s)", nullptr, 1))->setData(QVariant::fromValue(TimeDelta::fromDays(7)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n week(s)", nullptr, 2))->setData(QVariant::fromValue(TimeDelta::fromDays(14)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n week(s)", nullptr, 3))->setData(QVariant::fromValue(TimeDelta::fromDays(21)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n month(s)", nullptr, 1))->setData(QVariant::fromValue(TimeDelta::fromMonths(1)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n month(s)", nullptr, 2))->setData(QVariant::fromValue(TimeDelta::fromMonths(2)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n month(s)", nullptr, 3))->setData(QVariant::fromValue(TimeDelta::fromMonths(3)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n month(s)", nullptr, 6))->setData(QVariant::fromValue(TimeDelta::fromMonths(6)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n year(s)", nullptr, 1))->setData(QVariant::fromValue(TimeDelta::fromYears(1)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n year(s)", nullptr, 2))->setData(QVariant::fromValue(TimeDelta::fromYears(2)));
src/gui/entry/EditEntryWidget.cpp:    expirePresetsMenu->addAction(tr("%n year(s)", nullptr, 3))->setData(QVariant::fromValue(TimeDelta::fromYears(3)));
src/gui/entry/EntryAttachmentsWidget.cpp:                                       tr("Are you sure you want to remove %n attachment(s)?", "", indexes.count()),
src/gui/entry/EntryAttachmentsWidget.cpp:        errorMessage = tr("Unable to open file(s):\n%1", "", errors.size()).arg(errors.join('\n'));
src/gui/entry/EntryView.cpp:            listWidget.addItem(tr("+ %1 entry(s)...", nullptr, remaining).arg(remaining));
src/gui/reports/ReportsWidgetBrowserStatistics.cpp:    const auto delEntry = new QAction(icons()->icon("entry-delete"), tr("Delete Entry(s)…", "", selected.size()), this);
src/gui/reports/ReportsWidgetHealthcheck.cpp:    const auto delEntry = new QAction(icons()->icon("entry-delete"), tr("Delete Entry(s)…", "", selected.size()), this);
src/gui/reports/ReportsWidgetHibp.cpp:    const auto delEntry = new QAction(icons()->icon("entry-delete"), tr("Delete Entry(s)…", "", selected.size()), this);
src/gui/reports/ReportsWidgetPasskeys.cpp:    const auto delEntry = new QAction(icons()->icon("entry-delete"), tr("Delete Entry(s)…", "", selected.size()), this);
src/main.cpp:        "filename(s)", QObject::tr("filenames of the password databases to open (*.kdbx)"), "[filename(s)]");
```
