### ISSUE TITLE
Clipboard doesn't clear on KDE Plasma 6

### ISSUE THREAD

**Issue by greatbaracus** [keepassxreboot/keepassxc#10634]
## Overview
The clipboard does not get cleared after the time designated in the keepassxc GUI, and is present in the clipboard app history.

## Steps to Reproduce
1. Set clear clipboard sec to 10 secs
2. Copy an entry, wait 10 secs
3. Check clipboard, contents are still there

## Expected Behavior
The copied content should be absent from the clipbaord, along with the history.

## Actual Behavior
The password is still present in the clipboard and in the clipboard app history

## Context
Manjaro 23.1.4 Vulcan,  KDE Plasma X11 session, KeepassXC 2.7.7

There is a note on this point from Nate Graham [bugs.kde.org](https://bugs.kde.org/show_bug.cgi?id=470123#c1)

_....As you suspected, there is already a supported way for apps--which know whether something is a password--to provide a hint to Klipper to not display the text. They need to set the "x-kde-passwordManagerHint" metadata hint in the MIME data for the copied text. So IMO the path forward is for apps to set that on known-sensitive data when it's copied....._

If i may, i have the feeling, imho, specifically on this topic each one seems to offload the burden onto the other from a long time.
Frankly, i do not know who is right...

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/develop/src%2Fgui%2FClipboard.cpp#L59

We do, and it works.

There are some clipboard managers that do not respect this flag. Klipper does and I've tested it extensively.

**Comment by greatbaracus** [comment]
> https://github.com/keepassxreboot/keepassxc/blob/develop/src%2Fgui%2FClipboard.cpp#L59
> 
> We do, and it works.
> 
> There are some clipboard managers that do not respect this flag. Klipper does and I've tested it extensively.

That's is not what i am experiencing as a user, the password is not cleared...you could be wrong

**Comment by droidmonkey** [comment]
I'm certainly not wrong that we apply the Mime Data, it's been like that for years and working fine. Klipper could have regressed.

**Comment by droidmonkey** [comment]
This is your answer: https://discuss.kde.org/t/clipboard-doesnt-clear-after-password-copy-in-keepassxc/14717/8

When you copy text directly we don't apply the clearing algorithm because the copying is actually handled outside our app at that point.

**Comment by C0rn3j** [comment]
I just wanted to add an information point that it does work as intended on Wayland.  
It does not get saved in the clipboard history in the first place, and it does get cleared properly from the actual clipboard.

```yaml
keepassxc: 2.7.9

Operating System: Arch Linux 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
Memory: 62.0 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X670 AORUS ELITE AX
```
