### ISSUE TITLE
Q: Can you confirm the Ubuntu PPA is working on Debian Buster?

### ISSUE THREAD

**Issue by codekandis** [keepassxreboot/keepassxc#5375]
As the question proposes ... Can you confirm the Ubuntu PPA is working on Debian Buster?

I don't like to use the AppImage if I'm able to use an apt repository. This would make the update process much easier.

**Comment by droidmonkey** [comment]
Are you not able to confirm it?

**Comment by codekandis** [comment]
No, not yet. I'm as conservative as Debian.

My first attempt is to gather informations from the knowledge sources, which is you right here in this case. It's a reasonable guess you tried it already.

1. You're telling me "no, there are lib versions required which Debian doesn't provide" then this questions is answered and I'm not trying to mess around with my very stable system.
2. You're telling me "yes, we tried and we know all necessary libs are provided by Debian's repositories" it's quite cool.
3. You're telling me "no, we didn't try."

In case N° 3 I'm willing to try it on my on and to share my discoveries right here in this issue. And if there's any problem while there's no support with debian right now you maybe are able to fix them.

**Comment by droidmonkey** [comment]
None of the devs use Debian, so someone from the community would have to confirm.

**Comment by codekandis** [comment]
Ok, thank you. So I'm waiting a while. Maybe someone has informations.

**Comment by phoerious** [comment]
Just try it. The PPA doesn't contain any extra dependencies.

**Comment by codekandis** [comment]
I'm on the latest Debian Buster.

```none
deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic main
---
The following packages have unmet dependencies:
 keepassxc : Depends: libqrencode3 (>= 3.2.0) but it is not installable
```

I tried the codebase related to Debian Stretch.

```none
deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial main
---
The following packages have unmet dependencies:
 keepassxc : Depends: libqrencode3 (>= 3.2.0) but it is not installable
             Depends: libreadline6 (>= 6.0) but it is not installable
```

**Comment by phoerious** [comment]
Try the Eoan, Focal, or Groovy package. That should depend on libqrencode4. Bionic is too old.

**Comment by phoerious** [comment]
Cosmic and disco are both EOL.

**Comment by codekandis** [comment]
I know there is a way to install the single dependecies from external sources only. But this isn't worth the effort especially on my very stable system. On experimental systems maybe ...

So without further ado I wrote an Ansible role to install the latest App-Image.

And just in case someone is interrested.

```yaml
- name: Removing the outdated package `keepassxc`
  file:
    path: "path-to-keepassxc"
    state: absent

- block:
    - name: Determining the latest release version of the package `keepassxreboot/keepassxc` ... downloading GitHub releases website
      shell: "wget --quiet --output-document=- https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest"
      args:
        warn: false
      register: keepassxc_github_releases_api_response
    - name: Determining the latest release version of the package `ramboxapp/community-edition` ... setting release version variable
      set_fact:
        keepassxc_latest_release_version: "{{ keepassxc_github_releases_api_response.stdout | from_json | json_query( 'tag_name' ) }}"
    - name: Determining the latest release version of the package `ramboxapp/community-edition` ... setting asset URI
      set_fact:
        keepassxc_asset_uri: "{{ keepassxc_github_releases_api_response.stdout | from_json | json_query( 'assets[?name==`KeePassXC-' + keepassxc_latest_release_version + '-x86_64.AppImage`].browser_download_url' ) | first }}"

- block:
  - name: Downloading the package `keepassxc` ... creating the target directory
    file:
      path: "path-to-keepassxc"
      state: directory
      owner: username
      group: groupname
  - name: Downloading the package `keepassxc` ... downloading
    get_url:
      url: "{{ keepassxc_asset_uri }}"
      dest: "path-to-keepassxc/keepassxc"
      force: yes
      mode: 0700
      owner: username
      group: groupname
```

Obviously the `path-to-keepassxc`, `usernamename` and `groupname` should be replaced properly.
