### ISSUE TITLE
Snap: Automaticlly launch KeePassXC at system startup

### ISSUE THREAD

**Issue by Shempp** [keepassxreboot/keepassxc#7005]
## Overview
Functionality 'Automatically launch KeePassXC at system startup' does not work

## Steps to Reproduce
1. Install KeePassXC via snap or Ubuntu Software (snapcraft.io)
2. Set the option 'Automatically launch KeePassXC at system startup' to ON, click OK button
3. Restart the computer
4. Log to account

## Expected Behavior
KeePassXC start at system startup

## Actual Behavior
KeePassXC does not start

## Context
KeePassXC - 2.6.6
Revision: 9c108b9
Distributin: Snap

Operating System: Ubuntu 20.04.3 LTS
Desktop Env: Gnome
Windowing System: X11

A similar problem has been described in https://github.com/keepassxreboot/keepassxc/issues/5050
The entry in the "Startup Applications Preferences" does not appear

**Comment by droidmonkey** [comment]
Snaps can't access dot files so it is impossible to create an entry in ~/.config/autostart

**Comment by Shempp** [comment]
What about _autostart_ entry in _snapcraft.yaml_?
I do not know if this information will help, but in the [mattermost client](https://github.com/snapcrafters/mattermost-desktop) from snap it works.

**Comment by Nightmayr** [comment]
Autostart does appear to be possible for snaps, The desktop file is written to `$SNAP_USER_DATA/.config/autostart`. The documentation goes into more detail: https://snapcraft.io/docs/snap-format#heading--autostart

**Comment by droidmonkey** [comment]
We are not going to expend time to fix this, use the flatpak verison.

**Comment by JGCarroll** [comment]
Would you still accept a PR/suggestion to get this working?

The only thing that needs to be done in KeepassXC's case is changing `snapcraft.yaml` like so:

```
apps:
  keepassxc:
    command: usr/bin/keepassxc
    common-id: org.keepassxc.KeePassXC.desktop
    extensions: [kde-neon]
    plugs: [home, unity7, network, network-bind, removable-media, raw-usb]
    autostart: org.keepassxc.KeePassXC.desktop
```
I.E adding the autostart: field above
The existing code in the app doesn't require any modifications. After building the current master patched to use Core22, pressing the autostart option in the settings works exactly as expected.
